stages:
  stage_01_ingestion:
    cmd: python -m kedro run --pipeline stage_01_ingestion
    deps:
      - src/{{ python_package }}/jobs/01_ingestion.py
      - src/{{ python_package }}/kedro_nodes.py
      - src/{{ python_package }}/pipelines/stage_01_ingestion/pipeline.py
      - docker-compose.yml
    outs:
      - data/outputs/stage_01_ingestion

  stage_02_transformation:
    cmd: python -m kedro run --pipeline stage_02_transformation
    deps:
      - src/{{ python_package }}/jobs/02_transformation.py
      - src/{{ python_package }}/kedro_nodes.py
      - src/{{ python_package }}/pipelines/stage_02_transformation/pipeline.py
      - docker-compose.yml
    outs:
      - data/outputs/stage_02_transformation

  stage_03_delivery:
    cmd: python -m kedro run --pipeline stage_03_delivery
    deps:
      - src/{{ python_package }}/jobs/03_delivery.py
      - src/{{ python_package }}/kedro_nodes.py
      - src/{{ python_package }}/pipelines/stage_03_delivery/pipeline.py
      - docker-compose.yml
    outs:
      - data/outputs/stage_03_delivery
